import sys, gspread, pandas as pd
sys.stdout.reconfigure(encoding='utf-8')
gc = gspread.service_account(filename='credentials.json')
sh = gc.open_by_key('1B-QCbEnPpILFFEWPYheGdmkgYV9gSf4lAyQMlhzwOCM')
print("Title:", sh.title)
ws = sh.worksheet('CoCauVung')
data = ws.get_all_values()
df = pd.DataFrame(data[1:], columns=data[0])
print("Columns:", df.columns.tolist())
print(df.head(10))
